### ISSUE TITLE
Does not compile

### ISSUE THREAD

**Issue by WebFreak001** [jmeireles/cobox-wm#1]
First cloning recursively doesnt work (the submodule is broken)
Then when manually cloning it and modifying the dub file it has the wrong targetType
When then everything is changed it completely drowns in linker errors.

Tutorial on compiling would be nice because just doing `make` doesn't work

(OS: Ubuntu)

**Comment by jmeireles** [comment]
Hi,
Try.

cd /your/working/area
git clone https://github.com/D-Programming-Deimos/libX11
dub add-local libX11 0.0.1

and then dub build in the project, later this week i will make a proper read me.

**Comment by denizzzka** [comment]
Sucessful builds  for me on Debian by step-by-step instruction from README
