### ISSUE TITLE
wrong urls for images on code.dlang.org

### ISSUE THREAD

**Issue by denizzzka** [jmeireles/cobox-wm#3]
http://code.dlang.org/packages/cobox-wm

**Comment by jmeireles** [comment]
Hi,  it's been fixed, it shows a duplicated screenshot now but it's going to be updated soon.
Thanks alot for letting me know ! ;)

**Comment by denizzzka** [comment]
:з

I hope that it will replace me awesome wm

**Comment by jmeireles** [comment]
Alot of work to be done till that happens, but i'm pretty active and i'm quite using it most of the time ( replacing fluxbox), if you would like to join me you are more than welcome. Best Regards
